/*
 * pin_config.h
 *
 *  Created on: Jun 23, 2015
 *      Author: luaviskang
 */

#ifndef PIN_CONFIG_H_
#define PIN_CONFIG_H_

#define PIN_LINE_CAM_SI		100	//PG4 OUTPUT
#define PIN_LINE_CAM_CLOCK		101	//PG5 OUTPUT

#define PIN_LINE_CAM_1_ADC		1	// PB5 OUTPUT TOP

#define PIN_LINE_CAM_2_ADC		2	// PB6 OUTPUT RIGHT

#define PIN_LINE_CAM_3_ADC		3	// PB7 OUTPUT LEFT

#define PIN_TILT_SENSER_ADC 4

#define PIN_IR_SENSOR_1_ADC		6

#define PIN_IR_SENSOR_2_ADC		8

#define PIN_IR_SENSOR_3_ADC		10

#define PIN_IR_SENSOR_4_ADC		12

#define PIN_IR_SENSOR_5_ADC		14

#define PIN_MOTOR_ENABLE 2 // PA12 OUTPUT

#define PIN_LEFT_MOTOR_REVERSE 3 // PA13 OUTPUT

#define PIN_RIGHT_MOTOR_REVERSE 6 // PA14 OUTPUR

#define PIN_GLCD_CS 72 			//PE8

#define PIN_GLCD_RST 73 		//PE9

#define PIN_GLCD_AO 74 			//PE10

#define PIN_GLCD_SID 75 		//PE11

#define PIN_GLCD_SCLK 76 		//PE12

#define PIN_GLCD_LEDBLUE 77 	//PE13

#define PIN_GLCD_LEDGREEN 78 	//PE14

#define PIN_GLCD_LEDRED 79 		//PE15

#define PIN_SONA_SENSOR_ECHO 45

#define PIN_LEFT_ENCODER_REVERSE_PIN 42

#define PIN_RIGHT_ENCODER_REVERSE_PIN 43

#define PIN_BREAK_LIGHT 68

#define PIN_LEFT_DIR_LIGHT 69

#define PIN_RIGHT_DIR_LIGHT 70

#define PIN_4TH_LED		71

#endif /* PIN_CONFIG_H_ */
